import React from 'react';
const U='https://qktkeanebozuhwbrxdlg.supabase.co';
const K='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrdGtlYW5lYm96dWh3YnJ4ZGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0MjM0MTYsImV4cCI6MjA5NDk5OTQxNn0.fIfzqQ2pA2haK4iwGkY9x3LYDb4oFAID6XZY2VLZZGU';
const H={apikey:K,Authorization:'Bearer '+K,'Content-Type':'application/json'};
const C={card:'#fff',b:'#e5e7eb',t:'#111',s:'#6b7280',a:'#dc2626'};
const ST={draft:{bg:'#f3f4f6',c:'#6b7280',l:'Draft'},pending_pm:{bg:'#fef3c7',c:'#92400e',l:'Pending PM'},pending_accounts:{bg:'#dbeafe',c:'#1e40af',l:'Pending Accounts'},issued:{bg:'#d1fae5',c:'#065f46',l:'Issued'},rejected:{bg:'#fee2e2',c:'#991b1b',l:'Rejected'}};
const stOf=(s)=>ST[s]||ST.draft;
const roleLabel=(r)=>({project_manager:'Project Manager',accounts:'Accounts',estimation_sales:'Estimation',estimation_engineer:'Estimation',admin:'Admin',site_engineer:'Site Engineer'}[r]||r||'');
const esc=(x)=>String(x==null?'':x).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
export default function POProject({projectId,user,onCreatePO,onEditPO}){
const[pos,setPos]=React.useState([]);
const[loading,setLoading]=React.useState(true);
const[cs,setCs]=React.useState(null);
const[sel,setSel]=React.useState(null);
const[items,setItems]=React.useState([]);
const[appr,setAppr]=React.useState([]);
const[il,setIl]=React.useState(false);
const[cd,setCd]=React.useState(false);
const[del,setDel]=React.useState(false);
const[busy,setBusy]=React.useState(false);
const[rejMode,setRejMode]=React.useState(false);
const[rejText,setRejText]=React.useState('');
const isAdmin=user&&user.role==='admin';
const load=async()=>{setLoading(true);try{const r=await fetch(U+'/rest/v1/purchase_orders?project_id=eq.'+projectId+'&select=*,po_items(amount)&order=created_at.desc',{headers:H});if(r.ok)setPos(await r.json());}catch(e){console.error(e);}setLoading(false);};
React.useEffect(()=>{if(projectId)load();},[projectId]);
React.useEffect(()=>{fetch(U+'/rest/v1/company_settings?id=eq.1',{headers:H}).then(r=>r.ok?r.json():[]).then(d=>{if(d&&d[0])setCs(d[0]);}).catch(()=>{});},[]);
const tot=(p)=>(p.po_items||[]).reduce((s,x)=>s+(Number(x.amount)||0),0);
const loadAppr=async(poId)=>{try{const r=await fetch(U+'/rest/v1/po_approvals?po_id=eq.'+poId+'&order=created_at.asc',{headers:H});if(r.ok)setAppr(await r.json());}catch(e){console.error(e);}};
const getMe=async()=>{try{const r=await fetch(U+'/rest/v1/employees?email=eq.'+encodeURIComponent(user.email)+'&select=name,signature_url,designation',{headers:H});const d=r.ok?await r.json():[];return(d&&d[0])?d[0]:{};}catch(e){return{};}};
const open=async(po)=>{setSel(po);setItems([]);setAppr([]);setCd(false);setRejMode(false);setRejText('');setIl(true);try{const r=await fetch(U+'/rest/v1/po_items?po_id=eq.'+po.id+'&order=sl_no',{headers:H});if(r.ok)setItems(await r.json());}catch(e){console.error(e);}await loadAppr(po.id);setIl(false);};
const close=()=>{setSel(null);setItems([]);setAppr([]);setCd(false);setRejMode(false);setRejText('');};
const refreshSel=async()=>{try{const r=await fetch(U+'/rest/v1/purchase_orders?id=eq.'+sel.id+'&select=*,po_items(amount)',{headers:H});const d=r.ok?await r.json():[];if(d&&d[0])setSel(d[0]);}catch(e){console.error(e);}await loadAppr(sel.id);await load();};
const patchStatus=async(ns)=>{await fetch(U+'/rest/v1/purchase_orders?id=eq.'+sel.id,{method:'PATCH',headers:H,body:JSON.stringify({status:ns})});};
const logAppr=async(step,role,status,comments,me)=>{await fetch(U+'/rest/v1/po_approvals',{method:'POST',headers:H,body:JSON.stringify({po_id:sel.id,approver_role:role,approver_name:(me&&me.name)||(user&&(user.name||user.email))||'',approver_email:(user&&user.email)||'',approver_signature:(me&&me.signature_url)||null,approver_designation:(me&&me.designation)||null,status:status,comments:comments||null,approved_at:new Date().toISOString(),step_order:step})});};
const submit=async()=>{setBusy(true);try{const me=await getMe();await logAppr(0,user.role,'submitted',null,me);await patchStatus('pending_pm');await refreshSel();}catch(e){alert('Submit failed: '+e.message);}setBusy(false);};
const approve=async()=>{setBusy(true);try{const me=await getMe();if(sel.status==='pending_pm'){await logAppr(1,'project_manager','approved',null,me);await patchStatus('pending_accounts');}else if(sel.status==='pending_accounts'){await logAppr(2,'accounts','approved',null,me);await patchStatus('issued');}await refreshSel();}catch(e){alert('Approve failed: '+e.message);}setBusy(false);};
const reject=async()=>{setBusy(true);try{const me=await getMe();const step=sel.status==='pending_pm'?1:2;const role=sel.status==='pending_pm'?'project_manager':'accounts';await logAppr(step,role,'rejected',rejText,me);await patchStatus('draft');setRejMode(false);setRejText('');await refreshSel();}catch(e){alert('Reject failed: '+e.message);}setBusy(false);};
const remove=async()=>{setDel(true);try{await fetch(U+'/rest/v1/po_items?po_id=eq.'+sel.id,{method:'DELETE',headers:H});await fetch(U+'/rest/v1/po_approvals?po_id=eq.'+sel.id,{method:'DELETE',headers:H});await fetch(U+'/rest/v1/purchase_orders?id=eq.'+sel.id,{method:'DELETE',headers:H});close();await load();}catch(e){alert('Delete failed: '+e.message);}setDel(false);};
const total=items.reduce((s,it)=>s+(Number(it.amount)||0),0);
const canSubmit=sel&&sel.status==='draft';
const canActPM=sel&&sel.status==='pending_pm'&&(user.role==='project_manager'||user.role==='admin');
const canActAcc=sel&&sel.status==='pending_accounts'&&(user.role==='accounts'||user.role==='admin');
const canAct=canActPM||canActAcc;
const waitingNote=sel&&sel.status==='pending_pm'?'Waiting for Project Manager approval':sel&&sel.status==='pending_accounts'?'Waiting for Accounts approval':'';
const printPO=()=>{
const co=cs||{};
const atts=Array.isArray(sel.attachments)?sel.attachments:[];
const imgs=atts.filter(a=>a&&a.type&&a.type.indexOf('image')===0);
const rows=items.map((it,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(it.description)+'</td><td>'+esc(it.unit||'')+'</td><td class="r">'+(it.quantity||0)+'</td><td class="r">'+Number(it.rate||0).toLocaleString('en-IN')+'</td><td class="r">'+Number(it.amount||0).toLocaleString('en-IN')+'</td></tr>').join('');
const css='*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#1a1a1a;padding:32px;margin:0}.hdr{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #dc2626;padding-bottom:14px}.logo{width:25%;max-width:25%;height:auto;object-fit:contain}.po{text-align:right;min-width:235px}.pt{font-size:18px;font-weight:bold;letter-spacing:1px;color:#111;margin-bottom:6px}.meta{margin-left:auto;border-collapse:collapse;font-size:11px}.meta td{border:1px solid #ddd;padding:3px 8px}.meta td:first-child{color:#777;background:#f7f7f7;font-weight:600}.parties{display:flex;gap:16px;margin-top:18px}.party{flex:1;border:1px solid #e5e7eb;border-radius:6px;padding:10px 12px;font-size:11px;line-height:1.5}.lbl{font-size:9px;text-transform:uppercase;letter-spacing:.5px;color:#999;font-weight:700;margin-bottom:4px}.party .bb{font-weight:700;font-size:12px}.items{width:100%;border-collapse:collapse;margin-top:18px;font-size:11px}.items th,.items td{border:1px solid #ddd;padding:7px 9px}.items th{background:#f3f4f6;text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:.4px;color:#555}.items .r{text-align:right}.items tfoot td{font-weight:bold;background:#fafafa;font-size:12px}.terms{margin-top:12px;font-size:11px;line-height:1.55}.tl{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.5px;color:#999;font-weight:700;margin-bottom:2px}.quote{margin-top:18px}.quote img{width:100%;max-width:100%;border:1px solid #ddd;border-radius:4px;margin-top:8px;page-break-inside:avoid}.signs{display:flex;gap:24px;margin-top:46px;flex-wrap:wrap;page-break-inside:avoid}.sigbox{text-align:center;min-width:160px;flex:0 0 auto}.sigimg{height:48px;display:block;margin:0 auto 2px;object-fit:contain}.sigline{border-top:1px solid #999;padding-top:4px;font-size:11px;font-weight:700;margin-top:2px}.sigdesig{font-size:9.5px;color:#555;margin-top:1px}.foot{margin-top:18px;border-top:1px solid #eee;padding-top:8px;font-size:9.5px;color:#888;text-align:center}@media print{body{padding:14px}}';
const head='<div class="hdr">'+(co.logo_url?'<img src="'+co.logo_url+'" class="logo"/>':'<div style="font-size:20px;font-weight:bold">'+esc(co.company_name||'')+'</div>')+'<div class="po"><div class="pt">PURCHASE ORDER</div><table class="meta"><tr><td>PO No</td><td>'+esc(sel.po_number)+'</td></tr><tr><td>Date</td><td>'+new Date(sel.created_at).toLocaleDateString('en-IN')+'</td></tr><tr><td>Status</td><td>'+esc(stOf(sel.status).l)+'</td></tr></table></div></div>';
const parties='<div class="parties"><div class="party"><div class="lbl">Vendor</div><div class="bb">'+esc(sel.vendor_name)+'</div>'+(sel.vendor_address?'<div>'+esc(sel.vendor_address)+'</div>':'')+(sel.vendor_contact?'<div>Contact: '+esc(sel.vendor_contact)+'</div>':'')+(sel.vendor_email?'<div>'+esc(sel.vendor_email)+'</div>':'')+(sel.vendor_gstin?'<div>GSTIN: '+esc(sel.vendor_gstin)+'</div>':'')+'</div><div class="party"><div class="lbl">Project / Delivery</div><div class="bb">'+esc(sel.project_name||'')+'</div>'+(sel.project_code?'<div>'+esc(sel.project_code)+'</div>':'')+(sel.delivery_location?'<div>'+esc(sel.delivery_location)+'</div>':'')+(sel.delivery_date?'<div>Delivery Date: '+esc(sel.delivery_date)+'</div>':'')+'</div></div>';
const table=items.length>0?'<table class="items"><thead><tr><th>#</th><th>Description</th><th>Unit</th><th class="r">Qty</th><th class="r">Rate</th><th class="r">Amount</th></tr></thead><tbody>'+rows+'</tbody><tfoot><tr><td colspan="5" class="r">Total</td><td class="r">\u20b9'+total.toLocaleString('en-IN')+'</td></tr></tfoot></table>':'';
const quote=imgs.length>0?'<div class="quote"><span class="tl">Supplier Quote</span>'+imgs.map(a=>'<img src="'+a.url+'"/>').join('')+'</div>':'';
const terms=(sel.payment_terms?'<div class="terms"><span class="tl">Payment Terms</span>'+esc(sel.payment_terms)+'</div>':'')+(sel.terms_conditions?'<div class="terms"><span class="tl">Terms &amp; Conditions</span>'+esc(sel.terms_conditions)+'</div>':'')+(sel.remarks?'<div class="terms"><span class="tl">Remarks</span>'+esc(sel.remarks)+'</div>':'');
const signers=appr.filter(a=>a.status==='submitted'||a.status==='approved');
const company=co.company_name||'Maharaja Engineers & Contractors';
const signs=signers.length>0?'<div class="signs">'+signers.map(a=>'<div class="sigbox">'+(a.approver_signature?'<img class="sigimg" src="'+a.approver_signature+'"/>':'<div class="sigimg"></div>')+'<div class="sigline">'+esc(a.approver_name||'')+'</div><div class="sigdesig">'+esc((a.approver_designation||roleLabel(a.approver_role)))+', '+esc(company)+'</div></div>').join('')+'</div>':'<div class="signs"><div class="sigbox"><div class="sigimg"></div><div class="sigline">Authorized Signatory</div><div class="sigdesig">'+esc(company)+'</div></div></div>';
const foot='<div class="foot">'+[esc(co.address||''),(co.gstin?'GSTIN: '+esc(co.gstin):''),(co.phone?esc(co.phone):''),(co.email?esc(co.email):''),(co.website?esc(co.website):'')].filter(Boolean).join('  |  ')+'</div>';
const html='<!doctype html><html><head><meta charset="utf-8"><title>'+esc(sel.po_number)+'</title><style>'+css+'</style></head><body>'+head+parties+table+quote+terms+signs+foot+'<script>window.onload=function(){setTimeout(function(){window.print();},500);};</scr'+'ipt></body></html>';
const w=window.open('','_blank');if(!w){alert('Allow pop-ups to print');return;}w.document.write(html);w.document.close();w.focus();
};
const atts=sel&&Array.isArray(sel.attachments)?sel.attachments:[];
const aColor=(s)=>s==='approved'?'#065f46':s==='rejected'?'#991b1b':s==='submitted'?'#1e40af':'#6b7280';
const aWord=(s)=>s==='approved'?'Approved':s==='rejected'?'Rejected':s==='submitted'?'Submitted':s;
return(<div style={{padding:16}}>
<div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><div style={{fontSize:14,fontWeight:700,color:C.t}}>Purchase Orders</div><button onClick={onCreatePO} style={{padding:'7px 16px',background:C.a,color:'#fff',border:'none',borderRadius:7,fontSize:12,fontWeight:600,cursor:'pointer'}}>+ Create PO</button></div>
{loading?<div style={{textAlign:'center',color:C.s,padding:30,fontSize:13}}>Loading...</div>:pos.length===0?<div style={{textAlign:'center',color:C.s,padding:30,fontSize:13,background:C.card,border:'1px solid '+C.b,borderRadius:8}}>No purchase orders for this project yet</div>:(<div style={{border:'1px solid '+C.b,borderRadius:8,overflow:'hidden'}}>{pos.map((p,i)=>{const st=stOf(p.status);return(<div key={i} onClick={()=>open(p)} style={{padding:13,borderBottom:i<pos.length-1?'1px solid '+C.b:'none',background:C.card,cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:13,fontWeight:600,color:C.t}}>{p.po_number}</div><div style={{fontSize:11,color:C.s,marginTop:2}}>{p.vendor_name}</div></div><div style={{textAlign:'right'}}><div style={{fontSize:13,fontWeight:600,color:C.t}}>\u20b9{tot(p).toLocaleString('en-IN')}</div><span style={{display:'inline-block',padding:'2px 8px',borderRadius:10,fontSize:10,fontWeight:700,background:st.bg,color:st.c,marginTop:4}}>{st.l}</span></div></div></div>);})}</div>)}
{sel&&<div onClick={close} style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.5)',zIndex:9999,display:'flex',justifyContent:'center',alignItems:'flex-start',padding:20,overflowY:'auto'}}>
<div onClick={e=>e.stopPropagation()} style={{background:'#fff',borderRadius:12,maxWidth:720,width:'100%',padding:24,marginTop:10,marginBottom:40}}>
<div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:14}}><div><div style={{fontSize:17,fontWeight:700,color:C.t}}>{sel.po_number}</div><span style={{display:'inline-block',padding:'2px 10px',borderRadius:10,fontSize:10,fontWeight:700,marginTop:6,background:stOf(sel.status).bg,color:stOf(sel.status).c}}>{stOf(sel.status).l}</span></div><button onClick={close} style={{fontSize:18,background:'none',border:'none',cursor:'pointer',color:C.s}}>X</button></div>
<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14,marginBottom:16,fontSize:12,color:C.t}}>
<div><div style={{fontSize:10,color:C.s,textTransform:'uppercase',fontWeight:700,marginBottom:4}}>Vendor</div><div style={{fontWeight:600}}>{sel.vendor_name}</div>{sel.vendor_address&&<div style={{color:C.s,marginTop:2}}>{sel.vendor_address}</div>}{sel.vendor_contact&&<div style={{color:C.s,marginTop:2}}>Contact: {sel.vendor_contact}</div>}{sel.vendor_gstin&&<div style={{color:C.s,marginTop:2}}>GSTIN: {sel.vendor_gstin}</div>}</div>
<div style={{textAlign:'right'}}><div style={{fontSize:10,color:C.s,textTransform:'uppercase',fontWeight:700,marginBottom:4}}>Details</div><div>{sel.project_name}</div>{sel.delivery_date&&<div style={{color:C.s,marginTop:2}}>Delivery: {sel.delivery_date}</div>}<div style={{color:C.s,marginTop:2}}>By: {sel.created_by}</div></div>
</div>
{il?<div style={{textAlign:'center',color:C.s,padding:16,fontSize:12}}>Loading...</div>:items.length>0&&<div style={{border:'1px solid '+C.b,borderRadius:8,overflow:'hidden',marginBottom:14}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr style={{background:'#f3f4f6'}}><th style={{padding:8,textAlign:'left',fontSize:10,color:C.s}}>#</th><th style={{padding:8,textAlign:'left',fontSize:10,color:C.s}}>Description</th><th style={{padding:8,textAlign:'left',fontSize:10,color:C.s}}>Unit</th><th style={{padding:8,textAlign:'right',fontSize:10,color:C.s}}>Qty</th><th style={{padding:8,textAlign:'right',fontSize:10,color:C.s}}>Rate</th><th style={{padding:8,textAlign:'right',fontSize:10,color:C.s}}>Amount</th></tr></thead><tbody>{items.map((it,i)=>(<tr key={i} style={{borderTop:'1px solid '+C.b}}><td style={{padding:8}}>{i+1}</td><td style={{padding:8}}>{it.description}</td><td style={{padding:8}}>{it.unit}</td><td style={{padding:8,textAlign:'right'}}>{it.quantity}</td><td style={{padding:8,textAlign:'right'}}>{Number(it.rate||0).toLocaleString('en-IN')}</td><td style={{padding:8,textAlign:'right'}}>{Number(it.amount||0).toLocaleString('en-IN')}</td></tr>))}</tbody><tfoot><tr style={{borderTop:'2px solid '+C.b,fontWeight:700}}><td colSpan={5} style={{padding:8,textAlign:'right'}}>Total</td><td style={{padding:8,textAlign:'right'}}>\u20b9{total.toLocaleString('en-IN')}</td></tr></tfoot></table></div>}
{atts.length>0&&<div style={{marginTop:4,marginBottom:14}}><div style={{fontSize:10,color:C.s,textTransform:'uppercase',fontWeight:700,marginBottom:6}}>Supplier Quote / Attachments</div>{atts.map((a,i)=>(a.type&&a.type.indexOf('image')===0?<img key={i} src={a.url} alt={a.name} style={{width:'100%',borderRadius:8,border:'1px solid '+C.b,marginBottom:10,display:'block'}}/>:<a key={i} href={a.url} target="_blank" rel="noreferrer" style={{display:'inline-block',padding:'8px 14px',background:'#f3f4f6',borderRadius:8,fontSize:12,color:'#1d4ed8',textDecoration:'none',marginRight:8,marginBottom:8}}>PDF: {a.name||'Open'}</a>))}</div>}
{sel.payment_terms&&<div style={{marginBottom:8,fontSize:12}}><b>Payment Terms:</b> <span style={{color:C.s}}>{sel.payment_terms}</span></div>}
{sel.terms_conditions&&<div style={{marginBottom:8,fontSize:12}}><b>Terms &amp; Conditions:</b> <span style={{color:C.s}}>{sel.terms_conditions}</span></div>}
{sel.remarks&&<div style={{marginBottom:8,fontSize:12}}><b>Remarks:</b> <span style={{color:C.s}}>{sel.remarks}</span></div>}
{appr.length>0&&<div style={{marginTop:14,marginBottom:6,border:'1px solid '+C.b,borderRadius:8,padding:12}}><div style={{fontSize:10,color:C.s,textTransform:'uppercase',fontWeight:700,marginBottom:8}}>Approval History</div>{appr.map((a,i)=>(<div key={i} style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',paddingBottom:8,marginBottom:8,borderBottom:i<appr.length-1?'1px solid #f3f4f6':'none'}}><div style={{display:'flex',gap:10,alignItems:'center'}}>{a.approver_signature&&<img src={a.approver_signature} alt="sig" style={{height:30,objectFit:'contain'}}/>}<div><span style={{fontSize:12,fontWeight:700,color:aColor(a.status)}}>{aWord(a.status)}</span><span style={{fontSize:12,color:C.t}}> · {a.approver_designation||roleLabel(a.approver_role)}</span>{a.approver_name&&<div style={{fontSize:11,color:C.s,marginTop:1}}>{a.approver_name}</div>}{a.comments&&<div style={{fontSize:11,color:C.s,marginTop:2,fontStyle:'italic'}}>"{a.comments}"</div>}</div></div><div style={{fontSize:10,color:C.s,whiteSpace:'nowrap',marginLeft:10}}>{a.approved_at?new Date(a.approved_at).toLocaleDateString('en-IN'):''}</div></div>))}</div>}
{waitingNote&&!canAct&&<div style={{marginTop:12,padding:10,background:'#fef9c3',borderRadius:8,fontSize:12,color:'#854d0e',textAlign:'center'}}>{waitingNote}</div>}
{rejMode&&<div style={{marginTop:12}}><textarea rows={2} value={rejText} onChange={e=>setRejText(e.target.value)} placeholder="Reason for rejection (optional)" style={{width:'100%',padding:'9px 11px',border:'1px solid '+C.b,borderRadius:7,fontSize:12,boxSizing:'border-box',resize:'vertical'}}/></div>}
<div style={{display:'flex',gap:8,marginTop:18,flexWrap:'wrap'}}>
{canSubmit&&<button onClick={submit} disabled={busy} style={{flex:1,minWidth:140,padding:11,background:'#16a34a',color:'#fff',border:'none',borderRadius:8,fontWeight:700,cursor:'pointer'}}>{busy?'...':'Submit for Approval'}</button>}
{canAct&&!rejMode&&<button onClick={approve} disabled={busy} style={{flex:1,minWidth:120,padding:11,background:'#16a34a',color:'#fff',border:'none',borderRadius:8,fontWeight:700,cursor:'pointer'}}>{busy?'...':'Approve'}</button>}
{canAct&&!rejMode&&<button onClick={()=>setRejMode(true)} disabled={busy} style={{padding:'11px 18px',background:'#fee2e2',color:C.a,border:'none',borderRadius:8,fontWeight:700,cursor:'pointer'}}>Reject</button>}
{canAct&&rejMode&&<button onClick={reject} disabled={busy} style={{flex:1,minWidth:120,padding:11,background:C.a,color:'#fff',border:'none',borderRadius:8,fontWeight:700,cursor:'pointer'}}>{busy?'...':'Confirm Reject'}</button>}
{canAct&&rejMode&&<button onClick={()=>{setRejMode(false);setRejText('');}} style={{padding:'11px 18px',background:'#f3f4f6',color:C.t,border:'none',borderRadius:8,fontWeight:700,cursor:'pointer'}}>Cancel</button>}
<button onClick={printPO} style={{padding:'11px 18px',background:'#003366',color:'#fff',border:'none',borderRadius:8,fontWeight:700,cursor:'pointer'}}>Print PO</button>
{sel&&sel.status!=='issued'&&onEditPO&&<button onClick={()=>onEditPO({...sel,po_items:items})} style={{padding:'11px 18px',background:'#dbeafe',color:'#1d4ed8',border:'none',borderRadius:8,fontWeight:700,cursor:'pointer'}}>Edit</button>}
{isAdmin&&!cd&&<button onClick={()=>setCd(true)} style={{padding:'11px 18px',background:'#fee2e2',color:C.a,border:'none',borderRadius:8,fontWeight:700,cursor:'pointer'}}>Delete</button>}
{isAdmin&&cd&&<button onClick={remove} disabled={del} style={{padding:'11px 18px',background:C.a,color:'#fff',border:'none',borderRadius:8,fontWeight:700,cursor:'pointer'}}>{del?'Deleting...':'Confirm Delete'}</button>}
<button onClick={close} style={{padding:'11px 18px',background:'#f3f4f6',color:C.t,border:'none',borderRadius:8,fontWeight:700,cursor:'pointer'}}>Close</button>
</div>
</div></div>}
</div>);
}
